export const MAX_ACTIVE_BOOKINGS_PER_USER = 2;
export const MAX_BOOKING_ADVANCE_DAYS = 7;
export const MIN_BOOKING_LEAD_TIME_MINUTES = 15;
export const MIN_BOOKING_DURATION_MINUTES = 30;
export const MAX_BOOKING_DURATION_HOURS = 8;

export const MIN_BOOKING_LEAD_TIME_MS =
  MIN_BOOKING_LEAD_TIME_MINUTES * 60 * 1000;
export const MIN_BOOKING_DURATION_MS = MIN_BOOKING_DURATION_MINUTES * 60 * 1000;
export const MAX_BOOKING_DURATION_MS =
  MAX_BOOKING_DURATION_HOURS * 60 * 60 * 1000;
export const MAX_BOOKING_ADVANCE_MS =
  MAX_BOOKING_ADVANCE_DAYS * 24 * 60 * 60 * 1000;
